builds:
  - binary: hclwrite
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-w -s -X main.versionStr={{.Version}}"
archives:
  - files:
      - none* # do not include README
